# Generated by Django 5.0.7 on 2024-09-11 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_alter_faculty_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='faculty', to='login.subject'),
        ),
    ]
