# Generated by Django 5.0.7 on 2024-09-20 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_alter_faculty_subjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='labs',
        ),
        migrations.RemoveField(
            model_name='student',
            name='labs',
        ),
        migrations.DeleteModel(
            name='Lab',
        ),
    ]
