# Generated by Django 5.0.7 on 2024-09-30 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_remove_faculty_labs_remove_student_labs_delete_lab'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='noc_signed',
            field=models.BooleanField(default=False),
        ),
    ]
