# Generated by Django 5.0.7 on 2024-10-02 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_student_noc_signed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='noc_signed',
        ),
        migrations.CreateModel(
            name='StudentSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noc_signed', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.subject')),
            ],
            options={
                'unique_together': {('student', 'subject')},
            },
        ),
    ]
