# Generated by Django 5.0.7 on 2024-10-02 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_remove_student_noc_signed_studentsubject'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentsubject',
            unique_together=set(),
        ),
    ]
