# Generated by Django 5.0.7 on 2024-10-03 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_alter_studentsubject_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsubject',
            name='assignments_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
