# Generated by Django 5.0.7 on 2024-10-03 15:52

import login.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_studentsubject_assignments_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsubject',
            name='subject_attendance',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='studentsubject',
            name='subject_lab_attendance',
            field=models.IntegerField(),
        ),
    ]
